2023-09-07 21:41:10,466 ERROR: Exception on / [GET] [in /Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/app/main/routes.py", line 15, in before_request
    if current_user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
                    ^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/app/models.py", line 82, in load_user
    return User.query.get(int(id))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1131, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1140, in _get_impl
    return self.session._get_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3700, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/yokofutsukaichi/PycharmProject/microblog/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-09-07 21:43:38,963 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 21:43:43,975 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 21:43:49,711 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 21:43:53,629 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 21:50:26,942 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:09:29,739 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:12:10,060 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:22:19,915 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:30:07,631 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,332 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,347 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,347 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,388 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,388 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,388 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,422 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,422 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,422 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 22:57:16,422 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:40,969 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:40,994 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:40,994 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:41,039 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:41,039 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:41,039 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:41,072 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:41,072 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
2023-09-07 23:14:41,072 INFO: Microblog startup [in /Users/yokofutsukaichi/PycharmProject/microblog/app/__init__.py:80]
